-- Supabase/Postgres schema for the Retail POS desktop app.
-- Apply this in the Supabase SQL editor or with: supabase db push

create table if not exists public.roles (
    id bigint generated by default as identity primary key,
    name text not null unique,
    permissions text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    full_name text not null,
    role_id bigint references public.roles(id),
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.registers (
    id bigint generated by default as identity primary key,
    name text not null,
    location text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.cash_shifts (
    id bigint generated by default as identity primary key,
    register_id bigint not null references public.registers(id),
    user_id bigint not null references public.users(id),
    opened_at timestamptz not null default now(),
    closed_at timestamptz,
    opening_balance numeric(12, 2) not null default 0,
    closing_balance numeric(12, 2),
    expected_balance numeric(12, 2),
    status text not null default 'open'
);

create table if not exists public.cash_movements (
    id bigint generated by default as identity primary key,
    shift_id bigint not null references public.cash_shifts(id),
    user_id bigint references public.users(id),
    type text not null,
    amount numeric(12, 2) not null,
    reason text,
    created_at timestamptz not null default now()
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    barcode text unique,
    sku text unique,
    name text not null,
    price numeric(12, 2) not null,
    category text,
    stock_qty numeric(12, 3) not null default 0,
    requires_weight boolean not null default false,
    active boolean not null default true,
    image_path text,
    updated_at timestamptz not null default now()
);

create table if not exists public.product_barcodes (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    barcode text not null unique,
    is_primary boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.sales (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id),
    register_id bigint references public.registers(id),
    shift_id bigint references public.cash_shifts(id),
    total_amount numeric(12, 2) not null,
    payment_method text not null,
    tendered_amount numeric(12, 2) not null default 0,
    change_amount numeric(12, 2) not null default 0,
    note text,
    status text not null default 'completed',
    created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references public.sales(id) on delete cascade,
    product_id bigint references public.products(id),
    barcode text,
    name text,
    qty numeric(12, 3) not null,
    price numeric(12, 2) not null,
    subtotal numeric(12, 2) not null
);

create table if not exists public.sale_payments (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references public.sales(id) on delete cascade,
    method text not null,
    amount numeric(12, 2) not null,
    created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id),
    action text not null,
    table_name text,
    record_id bigint,
    old_values text,
    new_values text,
    created_at timestamptz not null default now()
);

create table if not exists public.settings (
    id bigint generated by default as identity primary key,
    key text not null unique,
    value text,
    updated_at timestamptz not null default now()
);

create table if not exists public.sync_queue (
    id bigint generated by default as identity primary key,
    entity_type text not null,
    entity_id bigint,
    operation text not null,
    payload text,
    status text not null default 'pending',
    retry_count integer not null default 0,
    last_error text,
    created_at timestamptz not null default now(),
    synced_at timestamptz
);

create table if not exists public.app_meta (
    key text primary key,
    value text
);

create index if not exists idx_users_username on public.users(username);
create index if not exists idx_roles_name on public.roles(name);
create index if not exists idx_registers_active on public.registers(active);
create index if not exists idx_cash_shifts_status on public.cash_shifts(status);
create index if not exists idx_cash_shifts_register on public.cash_shifts(register_id);
create index if not exists idx_cash_movements_shift on public.cash_movements(shift_id);
create index if not exists idx_audit_logs_created on public.audit_logs(created_at);
create index if not exists idx_products_barcode on public.products(barcode);
create index if not exists idx_product_barcodes_product on public.product_barcodes(product_id);
create index if not exists idx_product_barcodes_barcode on public.product_barcodes(barcode);
create index if not exists idx_products_sku on public.products(sku);
create index if not exists idx_products_name on public.products(name);
create index if not exists idx_sales_datetime on public.sales(created_at);
create index if not exists idx_sales_user on public.sales(user_id);
create index if not exists idx_sales_register on public.sales(register_id);
create index if not exists idx_sales_shift on public.sales(shift_id);
create index if not exists idx_sale_items_sale on public.sale_items(sale_id);
create index if not exists idx_sync_queue_status on public.sync_queue(status);

insert into public.roles (id, name, permissions)
values
    (1, 'Admin', 'all'),
    (2, 'Manager', 'sales,reports,products,registers,shifts,reconciliation'),
    (3, 'Cashier', 'sales,shifts')
on conflict (id) do nothing;

insert into public.users (username, password_hash, full_name, role_id)
values
    ('admin', 'sha256$240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Administrator', 1),
    ('manager', 'sha256$866485796cfa8d7c0cf7111640205b83076433547577511d81f8030ae99ecea5', 'Store Manager', 2),
    ('cashier', 'sha256$b4c94003c562bb0d89535eca77f07284fe560fd48a7cc1ed99f0a56263d616ba', 'Cashier', 3)
on conflict (username) do nothing;

insert into public.registers (name, location)
values ('Main Register', 'Store Front')
on conflict do nothing;

select setval(pg_get_serial_sequence('public.roles', 'id'), coalesce((select max(id) from public.roles), 1), true);
select setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1), true);
